name: Bug Report
description: Report a problem or unexpected behavior
title: '[BUG] '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Please describe the issue clearly so we can reproduce it.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or logs
      description: Add any visuals or console errors

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful...
